name: crit_care_des
channels:
  - conda-forge
dependencies:
  - flake8
  - jupyterlab=4.4.7
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.9.1
  - nbqa
  - numpy=2.0.1
  - pandas=2.2.2
  - python=3.11
  - scipy=1.14.0
  - simpy=4.1.1
  - sim-tools=0.10.0
